spring.application.name=estore-backend

# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3306/estore_db
spring.datasource.username=root
spring.datasource.password=Zineb@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB config
spring.data.mongodb.uri=mongodb://localhost:27017/estore_mongo